config/routes.rb
Rails.application.routes.draw do
  
  resources :alarms
  
  get 'welcome/index'
  

end

app/models/alarm.rb
class Alarm < ActiveRecord::Base
  validates :sitenr, presence: true
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  def index
    @alarms = Alarm.all
  end
  
  def new
    @alarm = Alarm.new
  end
  
  def show
    @alarm = Alarm.find(params[:id])
  end
  
  def create
    @alarm = Alarm.new(alarm_params)
    
    if @alarm.save
      redirect_to @alarm
    else
      render "new"
    end
  end
  
  def edit
    @alarm = Alarm.find(params[:id])
  end
  
  def update
    @alarm = Alarm.find(params[:id])
  
    if @alarm.update(alarm_params)
      redirect_to @alarm
    else
      render "edit"
    end
  end
  
  private
    def alarm_params
      params.require(:alarm).permit(:incidentnr, :sitenr, :customernr, :impnr, :status, :customername, :adress, :post)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/alarms/edit.html.erb
<h1>Editing alarm</h1>
 
<%= form_for :alarm, url: alarm_path(@alarm), method: :patch do |f| %>
  <% if @alarm.errors.any? %>
  	<div id="error_explanation">
    <h2><%= pluralize(@alarm.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
    	<% @alarm.errors.full_messages.each do |msg| %>
      		<li><%= msg %></li>
    	<% end %>
    </ul>
  </div>
  <% end %>
	<p>
		<%= f.label :incidentnr %><br>
		<%= f.number_field :incidentnr %>
	</p>
	
	<p>
		<%= f.label :sitenr %><br>
		<%= f.number_field :sitenr %>
	</p>
	<p>
		<%= f.label :customernr %><br>
		<%= f.number_field :customernr %>
	</p>
	<p>
		<%= f.label :impnr %><br>
		<%= f.number_field :impnr %>
	</p>
	<p>
		<%= f.label :status %><br>
		<%= f.text_field :status %>
	</p>
	<p>
		<%= f.label :customername %><br>
		<%= f.text_field :customername %>
	</p>
	<p>
		<%= f.label :adress %><br>
		<%= f.text_field :adress %>
	</p>
	<p>
		<%= f.label :post %><br>
		<%= f.text_field :post %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>
<%= link_to "Back", alarm_path %>

app/views/alarms/index.html.erb
<h1>listing alarms</h1>
<%= link_to "New alarm", new_alarm_path %>
<table>
	<tr>
		<th>incidentnr</th>
		<th>sitenr</th>
		<th>customernr</th>
		<th>impnr</th>
		<th>status</th>
		<th>customername</th>
		<th>adress</th>
		<th>post</th>
		<th>created at</th>
		<th>Updated at</th>
		<th>action</th>
	</tr>
	
	<% @alarms.each do |alarm| %>
		<tr>
			<td><%= alarm.incidentnr %></td>
			
			<td><%= alarm.sitenr %></td>
			<td><%= alarm.customernr %></td>
			<td><%= alarm.impnr %></td>
			<td><%= alarm.status %></td>
			<td><%= alarm.customername %></td>
			<td><%= alarm.adress %></td>
			<td><%= alarm.post %></td>
			<td><%= alarm.created_at%></td>
			<td><%= alarm.updated_at %></td>
			<td><%= link_to "Show", alarm_path(alarm) %></td>
			<td><%= link_to "Edit", edit_alarm_path(alarm) %></td>
		</tr>
	<% end %>
</table>

app/views/alarms/new.html.erb
<h1>New Alarm</h1>

<%= form_for :alarm, url: alarms_path do |f| %>
	<% if @alarm.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@alarm.errors.count, "error") %> prohibited
	      this article from being saved:</h2>
	    <ul>
	    <% @alarm.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	  <% end %>
	<p>
		<%= f.label :incidentnr %><br>
		<%= f.number_field :incidentnr %>
	</p>
	
	<p>
		<%= f.label :sitenr %><br>
		<%= f.number_field :sitenr %>
	</p>
	<p>
		<%= f.label :customernr %><br>
		<%= f.number_field :customernr %>
	</p>
	<p>
		<%= f.label :impnr %><br>
		<%= f.number_field :impnr %>
	</p>
	<p>
		<%= f.label :status %><br>
		<%= f.text_field :status %>
	</p>
	<p>
		<%= f.label :customername %><br>
		<%= f.text_field :customername %>
	</p>
	<p>
		<%= f.label :adress %><br>
		<%= f.text_field :adress %>
	</p>
	<p>
		<%= f.label :post %><br>
		<%= f.text_field :post %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
<% end %>
<%= link_to "Back", alarms_path %>

app/views/alarms/show.html.erb
<p>
	<strong>incidentnr:</strong>
	<%= @alarm.incidentnr %>
</p>
<p>
	<strong>sitenr:</strong>
	<%= @alarm.sitenr %>
</p>
<p>
	<strong>customernr:</strong>
	<%= @alarm.customernr %>
</p>
<p>
	<strong>impnr:</strong>
	<%= @alarm.incidentnr %>
</p>
<p>
	<strong>status:</strong>
	<%= @alarm.impnr %>
</p>

<p>
	<strong>customername:</strong>
	<%= @alarm.customername %>
</p>
<p>
	<strong>adress:</strong>
	<%= @alarm.adress %>
</p>
<p>
	<strong>post:</strong>
	<%= @alarm.post %>
</p>

<%= link_to "Back", alarms_path %>
| <%= link_to "Edit", edit_alarm_path(@alarm) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Button</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Button</h1>
<%= link_to "Alarms", controller: "alarms" %>